### ISSUE TITLE
進場紀錄api串接

### ISSUE THREAD

**Issue by shihKaiHung** [thereazon/havi-app#42]
<img width="597" alt="Screen Shot 2022-06-24 at 10 23 10 AM" src="https://user-images.githubusercontent.com/15310175/175449528-36de026b-a9a9-45dc-8165-6cd48e167480.png">

頁面: /checkin

參考api
<img width="1385" alt="Screen Shot 2022-06-24 at 10 23 24 AM" src="https://user-images.githubusercontent.com/15310175/175449561-d2c6fbf1-4909-40b8-96de-c655e71c134b.png">

**Comment by shihKaiHung** [comment]
預設派工單id會從/dispatch頁面帶在query string上

**Comment by shihKaiHung** [comment]
補充:
<img width="217" alt="Screen Shot 2022-06-24 at 10 48 47 AM" src="https://user-images.githubusercontent.com/15310175/175452286-1a22c903-0c54-4329-bd48-d34a5269fe88.png">
 
 這一塊改為不可以給user修改，統一由qs上的id為主

**Comment by abe1272001** [comment]
請問 BAC 酒測值要從哪裡取得？swagger 上是必帶的樣子

**Comment by shihKaiHung** [comment]
bac這個先隨便帶值1就好，目前畫面上沒提供
